### ISSUE TITLE
请教一下wiki.biligame的数据获取

### ISSUE THREAD

**Issue by FunJoo** [KevinZjYang/AnimalCrossing#2]
首先感谢作者做了UWP（泪目）。然后我就是想问这些数据是怎么从wiki.biligame上拿下来的，是有官方提供的API吗？

**Comment by KevinZjYang** [comment]
没有，使用python爬下来的，

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: FunJoo <notifications@github.com>
发送时间: Saturday, May 9, 2020 4:05:08 PM
收件人: KevinZjYang/AnimalCrossing <AnimalCrossing@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [KevinZjYang/AnimalCrossing] 请教一下wiki.biligame的数据获取 (#2)


首先感谢作者做了UWP（泪目）。然后我就是想问这些数据是怎么从wiki.biligame上拿下来的，是有官方提供的API吗？

―
